before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
language: python
python:
 - "3.6"
cache: pip
install:
 - pip install -r requirements.txt
script:
 - python Main.py
 